"""Shared constants for PlexAutoImport."""

from constants.inference import (
    CATEGORY_INPUT_SIZE,
    CATEGORY_LABELS,
    CATEGORY_THRESHOLD,
    CLASSIFY_CONFIDENCE_THRESHOLD,
    DEFAULT_CATEGORY_MODEL_FILENAME,
    IMAGENET_MEAN,
    IMAGENET_STD,
    LABEL_KEYWORDS,
    MAX_WORKING_RESOLUTION,
    MULTILABEL_MODEL_TYPES,
    TRAINING_IMAGE_SIZE,
)
from constants.media import (
    DEFAULT_EVENT_THRESHOLD,
    DURATION_THRESHOLD_SECONDS,
    IMAGE_EXTENSIONS,
    VIDEO_EXTENSIONS,
)
from constants.models import (
    FACE_DETECTOR_INPUT_HEIGHT,
    FACE_DETECTOR_INPUT_WIDTH,
    FACE_DETECTOR_MODEL_URL,
    FACE_IDENTIFIER_INPUT_SIZE,
    FACE_IDENTIFIER_MODEL_URL,
    FACE_NMS_IOU_THRESHOLD,
    MODEL_CACHE_DIR,
)
